### ISSUE TITLE
Texte dépassant de la big thumbnail

### ISSUE THREAD

**Issue by l00ma** [WildCodeSchool/0322_P3_Php_Lyon_Origins_Digital#41]
Lorsqu'on tape un texte long et sans espace dans la description de la big thumbnail, il dépasse:
![Capture d’écran du 2023-06-14 16-41-19](https://github.com/WildCodeSchool/0322_P3_Php_Lyon_Origins_Digital/assets/26147769/9e551b4d-41fa-4ff9-8fbf-bb5fe6e73739)

**Comment by maxdlr** [comment]
![image](https://github.com/WildCodeSchool/0322_P3_Php_Lyon_Origins_Digital/assets/105718327/78b26693-0637-4f4f-95d8-0d01082b820f)

En effet... Bizarrement ça marche sur les titres mais pas les descriptions.
